### ISSUE TITLE
Incorrect labeling of built-in pedigree in Shiny app

### ISSUE THREAD

**Issue by hnordto** [magnusdv/ibdsim2#17]
The following built-in pedigree is incorrectly labeled as _Half-sib incest_ in the `ibdsim2` Shiny app. Individual 7 and 8 are half first cousins and half siblings, but neither are inbred.

![ibdsim2_bug](https://github.com/user-attachments/assets/82969d40-86e4-4339-8508-894a1766939b)

**Comment by magnusdv** [comment]
Thanks, you are absolutely right. Fixed now, and added a couple more 'incestuous' pedigrees at the bottom of the list.
