### ISSUE TITLE
`haploDraw()` two outputs: first empty, second contains figure

### ISSUE THREAD

**Issue by mikldk** [magnusdv/ibdsim2#18]
The following - for me - produce two figures: the first is empty and the second contains the actual figure. I think it happened after an update:
``` r
library(ibdsim2)
#> Indlæser krævet pakke: pedtools
packageVersion("ibdsim2")
#> [1] '2.1.0'
set.seed(2)
chr1 <- loadMap("decode19", chrom = 1)
x1 <- nuclearPed(3)
x1 <- swapSex(x1, 3)
labs1 <- c("1" = "Far", 
           "2" = "Mor",
           "3" = "P1",
           "4" = "D1",
           "5" = "D2")
x1 <- relabel(x1, new = labs1)
sim1 <- ibdsim(x1, N = 1, map = chr1, verbose = FALSE)
haploDraw(x1, sim1, unit = "cm", pos = c(2, 4, 1, 1, 1), 
          symbolsize = 2,
          textAnnot = list(inside = x1$ID))
```

![](https://i.imgur.com/q3mu0JC.png)![](https://i.imgur.com/TuxsPXR.png)

<sup>Created on 2024-08-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mikldk** [comment]
If I insert

```r
png(filename = tempfile())
```
before the `pedtools::plot()` call at <https://github.com/magnusdv/ibdsim2/blob/624af6b15d77fcf9d6f6f7a622ea766ca96a4722/R/haploDraw.R#L170>
and 
```r
dev.off()
```
after, then it works.

So it seems like `pedtools::plot.ped()` opens a device although `plot = FALSE`.

**Comment by magnusdv** [comment]
Oh, that's a nice little bug.  Many thanks! 

Pushed a fix to GitHub now. Here is your example with the new version:
``` r
library(ibdsim2, quietly = T)
packageVersion("ibdsim2")
#> [1] '2.1.0.9000'

chr1 <- loadMap("decode19", chrom = 1)
x1 <- nuclearPed(fa = "Far", mo = "Mor", children = c("P1", "D1", "D2"), sex = c(2,1,1))
sim1 <- ibdsim(x1, N = 1, map = chr1, verbose = FALSE)

haploDraw(x1, sim1, unit = "cm", 
          pos = c(2, 4, 1, 1, 1), 
          symbolsize = 2,
          textAnnot = list(inside = x1$ID))
```

![](https://i.imgur.com/54cjW11.png)

<sup>Created on 2024-08-30 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by mikldk** [comment]
Thanks, @magnusdv !
